### ISSUE TITLE
Class Hierarchy

### ISSUE THREAD

**Issue by krishanudb** [seyedahbr/Wikidata_Reference_Statistics#1]
Hi,
I went through your paper and the code and found them very informative.
I am working on related areas, and had a few queries. It would be great if you can answer them.

For any KG, apart from the instance level information, it is also important to get information about the class hierarchy.

If I understand things properly, the wdumper json specification files (in gene_wiki) that is described in the repo can successfully extract instances of all the classes that are input. What I want to know is whether the wdumper json specifications that you shared in the repo also extracts the classes themselves and their hierarchy?

Thanks,
Krishanu.

**Comment by seyedahbr** [comment]
Hi Krishanu,

Thanks for your question. It's great you found the paper useful.

To extract the class hierarchy, you need to change the entity-value condition of the specification files. For example in Gene Wiki use case, you can take the initial file [active_site](https://github.com/seyedahbr/Wikidata_Reference_Statistics/blob/main/WDumper%20Specification%20Files/gene_wiki/active_site/active_site_RQ.json) and turn all `"property": "P31"` key-values to `"property": "P279"`. It will force WDumper to extract all classes that are subclasses (P279) of the initial classes (instead of instances (P31)). Repeat this for all Gene Wiki classes i.e. anatomical_structure, binding_site, and so on.

If you need to include the main classes, i.e. active_site, protein, gene, etc., you then add another entity-value condition to "entities" array with an empty property value. **Note that it is only can be interpreted by my WDumper forked repo, not the main repo by Benno**. I tweaked the code a bit so WDumper can understand a filter without a property value, but I didn't still raise a pull request. In the end, your ctive_site example will be something like this:
```
{
    "labels": true,
    "version": "1",
    "statements": [
        {
            "qualifiers": true,
            "id": 0,
            "simple": true,
            "rank": "all",
            "full": true,
            "references": true
        }
    ],
    "meta": true,
    "aliases": true,
    "sitelinks": true,
    "descriptions": true,
    "entities": [
        {
            "type": "item",
            "properties": [
                {
                    "type": "entityid",
                    "rank": "all"
                    "value": "Q423026",
                    "property": "P279"
                }
            ]
        }
        {
            "type": "item",
            "properties": [
                {
                    "type": "entityid",
                    "rank": "all"
                    "value": "Q423026",
                    "property": ""
                }
            ]
        }
    ]
}
```
Hope this answers your question! Please feel free for any comments.

Best,
Seyed

**Comment by krishanudb** [comment]
HI Seyed,
Thanks for providing such a detailed explanation.
It was really helpful. Thanks a ton.
Regards,
Krishanu.
